### ISSUE TITLE
not able to pull docker image in vagrant config

### ISSUE THREAD

**Issue by xrmx** [italia/docs-italia-deploy-scripts#11]
As there's no disk space in the image :) So we should not use it or find a workaround to have it working.

**Comment by yakky** [comment]
How about havign a larger image disk?
We can use a variable to set `settings.DOCKER_ENABLE`

**Comment by xrmx** [comment]
Resizing the image is a PITA, I'll take a look at building locally instead of using docker. But that's quite low priority

**Comment by xrmx** [comment]
Fixed, closing.
