### ISSUE TITLE
Stato pubblicazione privato per default

### ISSUE THREAD

**Issue by xrmx** [italia/docs-italia-deploy-scripts#22]
Per default lo stato di pubblicazione dei documenti deve essere private e non public

**Comment by yakky** [comment]
:thinking: lo stato non viene gestito qui. O ti riferisci a questa variabile   when: http == 1

**Comment by xrmx** [comment]
Intendo mettere un DEFAULT_PRIVACY_LEVEL = 'private' nel managed.py :)

**Comment by xrmx** [comment]
Perchè questa è stata revertata in 1683e392778f5c8128963c3551c8b12442852b01?

**Comment by xrmx** [comment]
@yakky ping

**Comment by xrmx** [comment]
PR che fa il revert del revert https://github.com/italia/docs-italia-deploy-scripts/pull/35
